### PR TITLE
Support animations in exported prototype

### PR DESCRIPTION
**Pull request by Lanfei**
Support animations in exported prototype (#2).

### CODE REVIEW

**Comment by romannurik** [comment]
Very cool! Any chance you could share a demo HTML output? I haven't had a ton of time to look into this lately, but will hopefully have time to review and merge soon.

**Comment by Lanfei** [comment]
Of course, here it is:

https://lanfei.github.io/Sketch-FlowExporter/

Generated source code:

https://github.com/Lanfei/Sketch-FlowExporter/blob/gh-pages/index.html

**Comment by Lanfei** [comment]
Hey, is there any feedback? :)

**Comment by romannurik** [comment]
Sorry it's been a very busy few months so I haven't had a chance to look. Will do asap

**Comment by Lanfei** [comment]
@romannurik 

It's ok, the animations are not urgent :)

I asked because I would like to fix the issue that [the hotspots in parent layer are covered by hotspots in symbol instance](https://github.com/romannurik/Sketch-FlowExporter/issues/1#issuecomment-441535866).

**Comment by romannurik** [comment]
@Lanfei could you file a separate issue about the hotspots in parent layers being covered, along with a simple example .sketch file that would show the problem?

**Comment by romannurik** [comment]
Also a couple of issues with this implementation just from my first glance:

* During transitions, the previous screen disappears... ideally it should remain on-screen while the new screen is animating in.
* Pressing Back (or clicking a target that goes Back) should probably play the reverse transition, rather than replaying the same transition

**Comment by Lanfei** [comment]
> During transitions, the previous screen disappears... ideally it should remain on-screen while the new screen is animating in.

Yes, it will be better if the previous artboard is visible during the transition.

> Pressing Back (or clicking a target that goes Back) should probably play the reverse transition, rather than replaying the same transition

Actually it is a issue of Sketch, when the target is the previous artboard, the animation type data from Sketch is always the same.

Anyway, I will close this PR and fire a new issue about hotspots, I will try to find a better solution if I have some free time :)

**Pull request closed without merging**
