### PR TITLE
Added an option to disable scrolling on the body.

### PR DESCRIPTION
**Pull request by lichtschlag**
I wanted to disable the body scroll bounce when the export is viewed on an iPad.

This pull request adds an option to do that. The setting defaults to the old behavior (scroll bounce enabled). I tested the code with the "fixed_scrolling.sketch" test file: the body does not scroll, the artboard contents still do.

Thank you for considering this pull request and thanks for this great plug-in.

### CODE REVIEW

**Comment by romannurik** [comment]
Pardon my ignorance, but would `overscroll-behavior: none` ([details](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior)) solve this?

**Comment by lichtschlag** [comment]
That is a good point—based on the description, this seems to be the clean solution! 
Unfortunately, iOS (12.3.1) does not respect this css-rule ([Can I Use](https://caniuse.com/#search=overscroll-behavior)). I tried this a moment ago as a property on `body` and can confirm, that it does not solve (my) problem.

**Comment by romannurik** [comment]
Sorry for the huge delay... since the only difference is `position: fixed` on `.prototype-container` i think this is safe for ALL exports, hence no need for the checkbox. i'm also including some more improvements for iOS exports (full-bleed exports) that hopefully should make prototypes look great on iPhone X and similar devices

**Comment by lichtschlag** [comment]
Just got a chance to test drive—looking good!

**Pull request closed without merging**
